import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';


type Page = 'home' | 'scan' | 'history' | 'profile' | 'events' | 'reports';
type EventItem = { title: string; date: string; time: string; place: string; kind: string; color: string; attending: number };

const ink = '#18251F';
const green = '#176B4A';
const muted = '#77827C';
const initialEvents: EventItem[] = [
  { title: 'Campus Clean-up Drive', date: 'OCT 04', time: '8:00 AM', place: 'Main Quadrangle', kind: 'COMMUNITY', color: '#DDF3E8', attending: 86 },
  { title: 'Student Leaders Assembly', date: 'OCT 08', time: '1:30 PM', place: 'Auditorium', kind: 'CAMPUS', color: '#E7E8FF', attending: 124 },
  { title: 'Tech Week 2026', date: 'OCT 12', time: '9:00 AM', place: 'Engineering Hall', kind: 'ACADEMIC', color: '#FFF0D8', attending: 203 },
];

function Label({ children }: { children: string }) { return <Text style={styles.label}>{children}</Text>; }
function Action({ title, onPress, light = false }: { title: string; onPress: () => void; light?: boolean }) {
  return <TouchableOpacity onPress={onPress} style={[styles.action, light && styles.actionLight]}><Text style={[styles.actionText, light && styles.actionTextLight]}>{title}</Text></TouchableOpacity>;
}
function EventCard({ item, onPress, button = 'View details' }: { item: EventItem; onPress: () => void; button?: string }) {
  return <View style={styles.eventCard}>
    <View style={styles.eventTop}><View style={[styles.dateBox, { backgroundColor: item.color }]}><Text style={styles.dateText}>{item.date.split(' ')[0]}</Text><Text style={styles.dateDay}>{item.date.split(' ')[1]}</Text></View>
      <View style={{ flex: 1 }}><Text style={styles.eventTitle}>{item.title}</Text><Text style={styles.eventMeta}>{item.time}  ·  {item.place}</Text></View><Text style={styles.dots}>···</Text></View>
    <View style={styles.eventBottom}><Text style={styles.tag}>{item.kind}</Text><TouchableOpacity onPress={onPress}><Text style={styles.link}>{button}  →</Text></TouchableOpacity></View>
  </View>;
}

export default function HomeScreen() {
  const [page, setPage] = useState<Page>('home');
  const [role, setRole] = useState<'Student' | 'Organizer'>('Student');
  const [signedIn, setSignedIn] = useState(true);
  const [name, setName] = useState('Alex Rivera');
  const [events, setEvents] = useState(initialEvents);
  const [scanned, setScanned] = useState(false);
  const [query, setQuery] = useState('');

  const signOut = () => { setSignedIn(false); setPage('home'); };
  const signIn = () => { setSignedIn(true); setPage('home'); };
  const addEvent = () => {
    setEvents([{ title: 'New campus gathering', date: 'OCT 18', time: '10:00 AM', place: 'Student Center', kind: 'CAMPUS', color: '#E7E8FF', attending: 0 }, ...events]);
    Alert.alert('Event created', 'Your new event is now on the event list.');
  };

  const header = (eyebrow: string, title: string, subtitle?: string) => <View style={styles.pageHead}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.pageTitle}>{title}</Text>{subtitle ? <Text style={styles.pageSubtitle}>{subtitle}</Text> : null}</View>;
  const dashboard = () => <>
    <View style={styles.topline}><View><Text style={styles.eyebrow}>MONDAY, SEPTEMBER 28</Text><Text style={styles.greeting}>Good morning, Alex <Text style={{ color: '#E5A847' }}>✦</Text></Text></View><TouchableOpacity style={styles.avatar} onPress={() => setPage('profile')}><Text style={styles.avatarText}>AR</Text></TouchableOpacity></View>
    <View style={styles.hero}><View style={styles.heroAccent}><Text style={styles.heroKicker}>YOUR CAMPUS, IN SYNC</Text><Text style={styles.heroTitle}>Show up.{ '\n' }Be counted.</Text><Text style={styles.heroCaption}>Every moment on campus matters.</Text><TouchableOpacity style={styles.heroButton} onPress={() => { setScanned(false); router.push('/scan'); }}><Text style={styles.heroButtonText}>▦   Scan attendance  →</Text></TouchableOpacity></View><View style={styles.heroOrb}><Text style={styles.orbGlyph}>✓</Text></View></View>
    <View style={styles.statsRow}><View style={styles.stat}><Text style={styles.statNumber}>12</Text><Text style={styles.statLabel}>EVENTS ATTENDED</Text><Text style={styles.statChange}>↑ 3 this month</Text></View><View style={styles.statDivider}/><View style={styles.stat}><Text style={styles.statNumber}>92<Text style={styles.percent}>%</Text></Text><Text style={styles.statLabel}>ATTENDANCE RATE</Text><Text style={styles.statChange}>Looking good!</Text></View></View>
    <View style={styles.sectionRow}><Label>UP NEXT</Label><TouchableOpacity onPress={() => setPage('events')}><Text style={styles.link}>See all  →</Text></TouchableOpacity></View>
    {events.slice(0, 2).map((event, i) => <EventCard key={`${event.title}-${i}`} item={event} onPress={() => Alert.alert(event.title, `${event.date} · ${event.time}\n${event.place}\n${event.attending} students attending`)} button="Details" />)}
    <View style={styles.tip}><Text style={styles.tipIcon}>✳</Text><View style={{ flex: 1 }}><Text style={styles.tipTitle}>You’re on a roll!</Text><Text style={styles.tipBody}>Attend 2 more events this month to beat your record.</Text></View><Text style={styles.tipArrow}>→</Text></View>
  </>;

  const scanPage = () => <>{header('CHECK IN', 'Scan to attend', 'Point your camera at the event QR code to record your attendance.')}
    <View style={styles.scanCard}><View style={[styles.scanFrame, scanned && styles.scanFrameDone]}>{scanned ? <Text style={styles.scanCheck}>✓</Text> : <><View style={[styles.corner, styles.cornerTL]}/><View style={[styles.corner, styles.cornerTR]}/><View style={[styles.corner, styles.cornerBL]}/><View style={[styles.corner, styles.cornerBR]}/><Text style={styles.scanGlyph}>▦</Text><View style={styles.scanLine}/></>}</View><Text style={styles.scanHint}>{scanned ? 'Attendance recorded!' : 'Camera preview'}</Text><Text style={styles.scanSub}>{scanned ? 'You’re checked in to Campus Clean-up Drive.' : 'Align the QR code inside the frame'}</Text></View>
    <View style={styles.notice}><Text style={styles.noticeIcon}>⌖</Text><View style={{ flex: 1 }}><Text style={styles.noticeTitle}>Location verification on</Text><Text style={styles.noticeBody}>You need to be at the event venue to check in.</Text></View><Text style={styles.greenDot}/></View>
    {!scanned ? <Action title="Simulate QR scan" onPress={() => setScanned(true)}/> : <Action title="Scan another code" light onPress={() => setScanned(false)}/>}</>;

  const historyPage = () => <>{header('YOUR ACTIVITY', 'Attendance history', 'A little consistency goes a long way.')}
    <View style={styles.historySummary}><View><Text style={styles.historyBig}>92%</Text><Text style={styles.historyCaption}>Overall attendance</Text></View><View style={styles.progressTrack}><View style={styles.progressFill}/></View><Text style={styles.streak}>✦  4 week streak</Text></View>
    <View style={styles.sectionRow}><Label>SEPTEMBER 2026</Label><Text style={styles.countPill}>4 events</Text></View>
    {[['26','Campus Clean-up Drive','Main Quadrangle','8:12 AM','PRESENT','#DDF3E8'],['21','Design Thinking Workshop','Innovation Lab','1:04 PM','PRESENT','#E7E8FF'],['16','General Assembly','University Auditorium','9:20 AM','PRESENT','#FFF0D8'],['08','Freshers Welcome Night','Open Grounds','—','ABSENT','#FBE5E2']].map((row, i) => <View key={i} style={styles.historyItem}><View style={[styles.historyDate, { backgroundColor: row[5] as string }]}><Text style={styles.historyDay}>{row[0]}</Text><Text style={styles.historyMonth}>SEP</Text></View><View style={{ flex: 1 }}><Text style={styles.historyTitle}>{row[1]}</Text><Text style={styles.historyVenue}>{row[2]}  ·  {row[3]}</Text></View><Text style={[styles.status, row[4] === 'ABSENT' && styles.statusAbsent]}>{row[4]}</Text></View>)}
    </>;

  const profilePage = () => <>{header('ACCOUNT', 'Your profile', 'Manage your CampusCount account.')}
    <View style={styles.profileCard}><View style={[styles.avatar, styles.profileAvatar]}><Text style={styles.avatarText}>{name.split(' ').map(x => x[0]).join('')}</Text></View><Text style={styles.profileName}>{name}</Text><Text style={styles.profileEmail}>alex.rivera@campus.edu</Text><Text style={styles.profileRole}>{role.toUpperCase()}  ·  COMPUTER SCIENCE</Text></View>
    <Label>PERSONAL INFORMATION</Label><Text style={styles.inputLabel}>Display name</Text><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="Your name" placeholderTextColor="#89938E"/><Text style={styles.inputLabel}>Email address</Text><TextInput value="alex.rivera@campus.edu" editable={false} style={[styles.input, styles.inputDisabled]}/>
    
    <Label>APP PREFERENCES</Label>
    
    <TouchableOpacity style={styles.settingRow} onPress={() => router.push('/id' as any)}>
      <Text style={styles.settingIcon}>▣</Text>
      <Text style={styles.settingName}>View Digital Student ID</Text>
      <Text style={styles.settingValue}>›</Text>
    </TouchableOpacity>

    <TouchableOpacity style={styles.settingRow} onPress={() => Alert.alert('Notifications', 'Event reminders are turned on.')}><Text style={styles.settingIcon}>♧</Text><Text style={styles.settingName}>Event notifications</Text><Text style={styles.settingValue}>On  ›</Text></TouchableOpacity>
    <TouchableOpacity style={styles.settingRow} onPress={() => setRole(role === 'Student' ? 'Organizer' : 'Student')}><Text style={styles.settingIcon}>⇄</Text><Text style={styles.settingName}>Switch account view</Text><Text style={styles.settingValue}>{role}  ›</Text></TouchableOpacity>
    <Action title="Sign out" light onPress={signOut}/>
    </>;

  const eventsPage = () => <>{header('CAMPUS LIFE', 'Events', 'Find your people. Make your mark.')}<TextInput value={query} onChangeText={setQuery} placeholder="⌕   Search events" placeholderTextColor="#87918B" style={styles.search}/><View style={styles.filterRow}><Text style={styles.filterActive}>All events</Text><Text style={styles.filter}>This week</Text><Text style={styles.filter}>My events</Text></View><View style={styles.sectionRow}><Label>UPCOMING</Label><Text style={styles.countPill}>{events.length} events</Text></View>{events.filter(e => e.title.toLowerCase().includes(query.toLowerCase())).map((e, i) => <EventCard key={`${e.title}-${i}`} item={e} onPress={() => Alert.alert(e.title, `${e.date} · ${e.time}\n${e.place}\n${e.attending} students attending`)} button="Register"/> )}</>;

  const reportsPage = () => <>{header('ORGANIZER TOOLS', 'Attendance report', 'A clear picture of campus participation.')}<View style={styles.reportBanner}><Text style={styles.reportLabel}>TOTAL CHECK-INS · THIS MONTH</Text><Text style={styles.reportNumber}>1,284</Text><Text style={styles.reportUp}>↗  18% more than August</Text></View><View style={styles.reportStats}><View style={styles.reportStat}><Text style={styles.reportStatNum}>86%</Text><Text style={styles.reportStatLabel}>AVG. TURNOUT</Text></View><View style={styles.reportStat}><Text style={styles.reportStatNum}>{events.length}</Text><Text style={styles.reportStatLabel}>EVENTS HELD</Text></View></View><Label>TOP ATTENDED EVENTS</Label>{events.slice(0, 3).map((e, i) => <View key={i} style={styles.reportRow}><View style={styles.reportRank}><Text style={styles.reportRankText}>0{i + 1}</Text></View><View style={{ flex: 1 }}><Text style={styles.historyTitle}>{e.title}</Text><Text style={styles.historyVenue}>{e.date} · {e.kind}</Text></View><Text style={styles.reportAttendance}>{e.attending} <Text style={styles.historyVenue}>people</Text></Text></View>)}<Action title="Export attendance CSV" onPress={() => Alert.alert('Report ready', 'Your attendance report is ready to export.')}/></>;

  const organizerPage = () => <>{header('ORGANIZER SPACE', 'Manage events', 'Bring your campus community together.')}<View style={styles.organizerBanner}><View><Text style={styles.orgEyebrow}>YOUR EVENTS</Text><Text style={styles.orgCount}>{events.length.toString().padStart(2, '0')}</Text><Text style={styles.orgCaption}>events on the calendar</Text></View><Text style={styles.orgDecoration}>✳</Text></View><Action title="＋   Create a new event" onPress={addEvent}/><View style={styles.sectionRow}><Label>EVENT CALENDAR</Label><Text style={styles.countPill}>OCTOBER</Text></View>{events.map((e, i) => <EventCard key={`${e.title}-${i}`} item={e} onPress={() => Alert.alert(e.title, `${e.attending} attendees · ${e.place}`, [{ text: 'Close' }, { text: 'View report', onPress: () => setPage('reports') }])} button="Manage"/>)}<TouchableOpacity style={styles.reportShortcut} onPress={() => setPage('reports')}><Text style={styles.reportShortcutIcon}>▤</Text><View style={{ flex: 1 }}><Text style={styles.settingName}>Attendance reports</Text><Text style={styles.historyVenue}>Turnout analytics and exports</Text></View><Text style={styles.link}>Open →</Text></TouchableOpacity></>;

  const navItems: { id: Page; icon: string; label: string }[] = role === 'Student' ? [{ id: 'home', icon: '⌂', label: 'Home' }, { id: 'events', icon: '▦', label: 'Events' }, { id: 'scan', icon: '▣', label: 'Check in' }, { id: 'history', icon: '◷', label: 'History' }, { id: 'profile', icon: '○', label: 'Profile' }] : [{ id: 'home', icon: '⌂', label: 'Home' }, { id: 'events', icon: '▦', label: 'Events' }, { id: 'reports', icon: '▤', label: 'Reports' }, { id: 'profile', icon: '○', label: 'Profile' }];

  if (!signedIn) return <SafeAreaView style={styles.loginScreen}><StatusBar barStyle="dark-content"/><View style={styles.loginLogo}><Text style={styles.logoGlyph}>✓</Text></View><Text style={styles.brand}>campus<Text style={{ color: green }}>count</Text></Text><Text style={styles.loginTitle}>Your campus life,{ '\n' }all in one place.</Text><Text style={styles.loginSubtitle}>Track attendance, discover events, and stay connected with your campus community.</Text><Text style={styles.inputLabel}>SCHOOL EMAIL</Text><TextInput style={styles.input} placeholder="you@campus.edu" placeholderTextColor="#89938E" keyboardType="email-address" autoCapitalize="none"/><Text style={styles.inputLabel}>PASSWORD</Text><TextInput style={styles.input} placeholder="Enter your password" placeholderTextColor="#89938E" secureTextEntry/><Action title="Sign in  →" onPress={signIn}/><Text style={styles.loginFoot}>A better campus experience starts here.</Text></SafeAreaView>;

  return <SafeAreaView style={styles.safe} edges={['top']}><StatusBar barStyle="dark-content" backgroundColor="#F7F8F5"/><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{role === 'Organizer' && page === 'home' ? organizerPage() : page === 'home' ? dashboard() : page === 'scan' ? scanPage() : page === 'history' ? historyPage() : page === 'profile' ? profilePage() : page === 'events' ? eventsPage() : reportsPage()}</ScrollView><View style={styles.bottomNav}>{navItems.map(item => <TouchableOpacity key={item.id} style={styles.navItem} onPress={() => {
    if (item.id === 'scan') {
      router.push('/scan');
    } else {
      setPage(item.id);
    }
  }}><Text style={[styles.navIcon, page === item.id && styles.navActive]}>{item.icon}</Text><Text style={[styles.navLabel, page === item.id && styles.navActive]}>{item.label}</Text></TouchableOpacity>)}</View></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F7F8F5' }, content: { paddingHorizontal: 22, paddingTop: 14, paddingBottom: 28 },
  topline: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 21 }, eyebrow: { color: muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.35 }, greeting: { color: ink, fontSize: 23, fontWeight: '800', marginTop: 7, letterSpacing: -0.6 }, avatar: { width: 43, height: 43, borderRadius: 15, backgroundColor: '#DCEFE3', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: green, fontWeight: '800', fontSize: 14 },
  hero: { minHeight: 204, borderRadius: 23, backgroundColor: '#155E43', padding: 22, overflow: 'hidden', marginBottom: 14, flexDirection: 'row' }, heroAccent: { zIndex: 2 }, heroKicker: { color: '#A7D1B7', fontSize: 9, fontWeight: '800', letterSpacing: 1.5 }, heroTitle: { color: '#FFFFFF', fontWeight: '800', fontSize: 31, lineHeight: 34, marginTop: 9, letterSpacing: -0.9 }, heroCaption: { color: '#CEE3D5', fontSize: 12, marginTop: 7 }, heroButton: { marginTop: 16, backgroundColor: '#F2F7F0', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 11, alignSelf: 'flex-start' }, heroButtonText: { color: green, fontSize: 11, fontWeight: '800' }, heroOrb: { position: 'absolute', width: 152, height: 152, borderRadius: 90, backgroundColor: '#247452', right: -27, top: 32, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-12deg' }] }, orbGlyph: { color: '#B3DFC4', fontSize: 71, fontWeight: '200' },
  statsRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 17, paddingVertical: 16, marginBottom: 25, borderWidth: 1, borderColor: '#ECEFEB' }, stat: { flex: 1, paddingHorizontal: 18 }, statDivider: { width: 1, height: 44, backgroundColor: '#E8ECE8' }, statNumber: { color: ink, fontSize: 24, fontWeight: '800', letterSpacing: -0.7 }, percent: { fontSize: 15 }, statLabel: { color: muted, fontSize: 8, fontWeight: '800', letterSpacing: 0.8, marginTop: 2 }, statChange: { color: green, fontSize: 10, fontWeight: '700', marginTop: 7 },
  label: { color: muted, fontSize: 9, fontWeight: '800', letterSpacing: 1.2, marginBottom: 11 }, sectionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }, link: { color: green, fontWeight: '800', fontSize: 11 }, eventCard: { backgroundColor: '#FFFFFF', padding: 14, borderRadius: 16, borderWidth: 1, borderColor: '#ECEFEB', marginBottom: 10 }, eventTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, dateBox: { width: 45, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, dateText: { color: ink, fontSize: 9, fontWeight: '800', letterSpacing: 0.7 }, dateDay: { color: ink, fontSize: 17, fontWeight: '800', marginTop: 1 }, eventTitle: { color: ink, fontSize: 13, fontWeight: '800' }, eventMeta: { color: muted, fontSize: 10, marginTop: 5 }, dots: { color: muted, fontSize: 17, marginTop: -9 }, eventBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderColor: '#F0F1EF' }, tag: { color: green, backgroundColor: '#E9F4EC', paddingVertical: 5, paddingHorizontal: 8, borderRadius: 6, fontSize: 8, fontWeight: '800', letterSpacing: 0.6 },
  tip: { flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: '#FFF5DF', borderRadius: 15, padding: 14, marginTop: 5 }, tipIcon: { fontSize: 21, color: '#D59625' }, tipTitle: { color: ink, fontSize: 12, fontWeight: '800' }, tipBody: { color: '#77776F', fontSize: 10, marginTop: 4 }, tipArrow: { color: '#B78224', fontSize: 17 },
  pageHead: { marginTop: 12, marginBottom: 23 }, pageTitle: { fontSize: 27, lineHeight: 32, color: ink, fontWeight: '800', letterSpacing: -0.7, marginTop: 7 }, pageSubtitle: { color: muted, fontSize: 12, lineHeight: 18, marginTop: 7 }, scanCard: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 20, alignItems: 'center', borderWidth: 1, borderColor: '#ECEFEB' }, scanFrame: { width: 230, height: 230, backgroundColor: '#F2F5F1', borderRadius: 16, alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' }, scanFrameDone: { backgroundColor: '#E5F4EA' }, scanGlyph: { color: '#AFBDB2', fontSize: 74 }, scanLine: { position: 'absolute', width: 178, height: 2, backgroundColor: '#38A36D', top: 112, opacity: 0.75 }, scanCheck: { color: green, fontSize: 72, fontWeight: '700' }, corner: { position: 'absolute', width: 29, height: 29, borderColor: green }, cornerTL: { top: 16, left: 16, borderTopWidth: 3, borderLeftWidth: 3, borderTopLeftRadius: 8 }, cornerTR: { top: 16, right: 16, borderTopWidth: 3, borderRightWidth: 3, borderTopRightRadius: 8 }, cornerBL: { bottom: 16, left: 16, borderBottomWidth: 3, borderLeftWidth: 3, borderBottomLeftRadius: 8 }, cornerBR: { bottom: 16, right: 16, borderBottomWidth: 3, borderRightWidth: 3, borderBottomRightRadius: 8 }, scanHint: { color: ink, fontSize: 14, fontWeight: '800', marginTop: 19 }, scanSub: { color: muted, fontSize: 11, marginTop: 6, textAlign: 'center' }, notice: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 15, backgroundColor: '#FFFFFF', borderRadius: 14, borderColor: '#ECEFEB', borderWidth: 1, marginTop: 14, marginBottom: 18 }, noticeIcon: { color: green, fontSize: 20 }, noticeTitle: { color: ink, fontWeight: '700', fontSize: 11 }, noticeBody: { color: muted, fontSize: 10, marginTop: 4 }, greenDot: { backgroundColor: '#3FA96D', width: 8, height: 8, borderRadius: 4 }, action: { minHeight: 47, borderRadius: 13, backgroundColor: green, alignItems: 'center', justifyContent: 'center', marginTop: 12, marginBottom: 16 }, actionText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' }, actionLight: { backgroundColor: '#FFFFFF', borderColor: '#E4E9E4', borderWidth: 1 }, actionTextLight: { color: green },
  historySummary: { backgroundColor: '#165F44', padding: 19, borderRadius: 18, marginBottom: 24 }, historyBig: { color: '#FFFFFF', fontSize: 30, fontWeight: '800' }, historyCaption: { color: '#D1E7D7', fontSize: 10, marginTop: 1 }, progressTrack: { height: 6, backgroundColor: '#467E62', borderRadius: 8, marginTop: 17 }, progressFill: { width: '92%', height: 6, backgroundColor: '#B8E2C6', borderRadius: 8 }, streak: { color: '#D8EDE0', fontSize: 10, fontWeight: '700', marginTop: 11 }, countPill: { color: '#647169', fontSize: 9, fontWeight: '700', backgroundColor: '#EEF1ED', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8 }, historyItem: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13, borderBottomWidth: 1, borderColor: '#E9EDE8' }, historyDate: { width: 42, height: 46, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, historyDay: { color: ink, fontSize: 17, fontWeight: '800' }, historyMonth: { color: muted, fontSize: 8, fontWeight: '800' }, historyTitle: { color: ink, fontSize: 11, fontWeight: '800' }, historyVenue: { color: muted, fontSize: 9, marginTop: 4 }, status: { color: green, fontSize: 8, fontWeight: '800', letterSpacing: 0.4 }, statusAbsent: { color: '#B86654' },
  profileCard: { alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 21, marginBottom: 23, borderWidth: 1, borderColor: '#ECEFEB' }, profileAvatar: { width: 67, height: 67, borderRadius: 23, marginBottom: 11 }, profileName: { color: ink, fontSize: 18, fontWeight: '800' }, profileEmail: { color: muted, fontSize: 11, marginTop: 5 }, profileRole: { color: green, fontSize: 8, fontWeight: '800', letterSpacing: 1, backgroundColor: '#E9F4EC', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 7, marginTop: 12 }, inputLabel: { color: muted, fontSize: 9, fontWeight: '800', letterSpacing: 0.8, marginTop: 13, marginBottom: 7 }, input: { minHeight: 46, borderRadius: 11, borderWidth: 1, borderColor: '#E5EAE5', backgroundColor: '#FFFFFF', paddingHorizontal: 13, color: ink, fontSize: 12, marginBottom: 3 }, inputDisabled: { color: '#99A29D', marginBottom: 22 }, settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderColor: '#E9EDE8', gap: 10 }, settingIcon: { color: green, fontSize: 17, width: 25 }, settingName: { flex: 1, color: ink, fontSize: 11, fontWeight: '700' }, settingValue: { color: muted, fontSize: 10 },
  search: { minHeight: 45, backgroundColor: '#FFFFFF', borderRadius: 12, paddingHorizontal: 13, borderWidth: 1, borderColor: '#E9EDE8', color: ink, fontSize: 12 }, filterRow: { flexDirection: 'row', gap: 9, marginVertical: 14 }, filterActive: { overflow: 'hidden', color: '#FFFFFF', backgroundColor: green, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 8, fontSize: 9, fontWeight: '700' }, filter: { overflow: 'hidden', color: '#67736B', backgroundColor: '#ECEFEB', borderRadius: 8, paddingHorizontal: 11, paddingVertical: 8, fontSize: 9, fontWeight: '700' },
  reportBanner: { backgroundColor: '#165F44', borderRadius: 18, padding: 20, marginBottom: 12 }, reportLabel: { color: '#C2DECC', fontSize: 9, fontWeight: '800', letterSpacing: 1 }, reportNumber: { color: '#FFFFFF', fontSize: 41, fontWeight: '800', marginTop: 9 }, reportUp: { color: '#B8E2C6', fontSize: 10, marginTop: 5 }, reportStats: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEFEB', borderRadius: 15, paddingVertical: 16, marginBottom: 23 }, reportStat: { flex: 1, alignItems: 'center' }, reportStatNum: { color: ink, fontSize: 22, fontWeight: '800' }, reportStatLabel: { color: muted, fontSize: 8, fontWeight: '800', letterSpacing: 0.7, marginTop: 4 }, reportRow: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13, borderBottomWidth: 1, borderColor: '#E9EDE8' }, reportRank: { height: 35, width: 35, backgroundColor: '#E9F4EC', borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, reportRankText: { color: green, fontSize: 10, fontWeight: '800' }, reportAttendance: { color: ink, fontSize: 12, fontWeight: '800' },
  organizerBanner: { backgroundColor: '#165F44', borderRadius: 18, padding: 19, marginBottom: 3, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, orgEyebrow: { color: '#C2DECC', fontSize: 9, fontWeight: '800', letterSpacing: 1 }, orgCount: { color: '#FFFFFF', fontSize: 34, fontWeight: '800', marginTop: 4 }, orgCaption: { color: '#D1E7D7', fontSize: 10 }, orgDecoration: { color: '#B8E2C6', fontSize: 45 }, reportShortcut: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 15, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEFEB', borderRadius: 14, marginTop: 8 }, reportShortcutIcon: { color: green, fontSize: 20 },
  bottomNav: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderTopWidth: 1, borderColor: '#EAEEEA', paddingTop: 9, paddingBottom: 5, justifyContent: 'space-around' }, navItem: { alignItems: 'center', justifyContent: 'center', minWidth: 54 }, navIcon: { fontSize: 20, color: '#98A29C' }, navLabel: { fontSize: 8, color: '#98A29C', marginTop: 3, fontWeight: '600' }, navActive: { color: green, fontWeight: '800' },
  loginScreen: { flex: 1, justifyContent: 'center', backgroundColor: '#F7F8F5', paddingHorizontal: 27 }, loginLogo: { width: 48, height: 48, borderRadius: 16, backgroundColor: green, alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, logoGlyph: { color: '#FFFFFF', fontSize: 27, fontWeight: '700' }, brand: { color: ink, fontSize: 20, fontWeight: '800' }, loginTitle: { color: ink, fontSize: 35, lineHeight: 39, fontWeight: '800', letterSpacing: -1, marginTop: 43 }, loginSubtitle: { color: muted, fontSize: 13, lineHeight: 20, marginTop: 11, marginBottom: 24 }, loginFoot: { textAlign: 'center', color: muted, fontSize: 10, marginTop: 15 },
});